style = "sciml"
whitespace_in_kwargs = false
format_docstrings = true
separate_kwargs_with_semicolon = true
format_markdown = true
annotate_untyped_fields_with_any = false
join_lines_based_on_source = false
