name: Documentation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch || github.ref != 'refs/tags/v*' }}

jobs:
  docs:
    name: "Documentation"
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
