name: Downgrade
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  downgrade:
    if: false  # Disabled: waiting on SciML ecosystem updates. See #193 for details.
    name: "Downgrade"
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "1.10"
      skip: "Pkg,TOML"
    secrets: "inherit"
